# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  fl_joint1:
    has_velocity_limits: true
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 0
  fl_joint2:
    has_velocity_limits: true
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 0
  fl_joint3:
    has_velocity_limits: true
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 0
  fl_joint4:
    has_velocity_limits: true
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 0
  fl_joint5:
    has_velocity_limits: true
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 0
  fl_joint6:
    has_velocity_limits: true
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 0
  fl_joint7:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  fl_joint8:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  fr_joint1:
    has_velocity_limits: true
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 0
  fr_joint2:
    has_velocity_limits: true
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 0
  fr_joint3:
    has_velocity_limits: true
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 0
  fr_joint4:
    has_velocity_limits: true
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 0
  fr_joint5:
    has_velocity_limits: true
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 0
  fr_joint6:
    has_velocity_limits: true
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 0
  fr_joint7:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  fr_joint8:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  lr_joint1:
    has_velocity_limits: true
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 0
  lr_joint2:
    has_velocity_limits: true
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 0
  lr_joint3:
    has_velocity_limits: true
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 0
  lr_joint4:
    has_velocity_limits: true
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 0
  lr_joint5:
    has_velocity_limits: true
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 0
  lr_joint6:
    has_velocity_limits: true
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 0
  lr_joint7:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  lr_joint8:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  rr_joint1:
    has_velocity_limits: true
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 0
  rr_joint2:
    has_velocity_limits: true
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 0
  rr_joint3:
    has_velocity_limits: true
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 0
  rr_joint4:
    has_velocity_limits: true
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 0
  rr_joint5:
    has_velocity_limits: true
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 0
  rr_joint6:
    has_velocity_limits: true
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 0
  rr_joint7:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  rr_joint8:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0